### ISSUE TITLE
Add privacy policy to website

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-website#153]
# Introduction

We have finally agreed on a privacy policy we feel somewhat comfortable to add in our website. We are likely going to tweak a few things, but for now, we'll stick with the attached version.

# Task Description
- [ ] Use `react-pdf` (see other files in the repository under Press Releases) to render our privacy policy from the attached PDF into our website under the URL https://horpnet.org/privacy-policy

# Additional Notes
[ZURICH-#673229-v1-HOPR__privacy_statement_(e).DOCX.pdf](https://github.com/hoprnet/website-hoprnet-org/files/5584972/ZURICH-.673229-v1-HOPR__privacy_statement_.e.DOCX.pdf)

**Comment by betinho89** [comment]
Ready.
3c4cdb5a3fda8fd71b0fa3ff7cfb33e253008ebf
cfbfb62cdae2aa4fff57805f50684adf382a83d0

**Comment by betinho89** [comment]
Done!
#154

**Comment by betinho89** [comment]
> # Introduction
> We have finally agreed on a privacy policy we feel somewhat comfortable to add in our website. We are likely going to tweak a few things, but for now, we'll stick with the attached version.
> 
> # Task Description
> * [x ]  Use `react-pdf` (see other files in the repository under Press Releases) to render our privacy policy from the attached PDF into our website under the URL https://horpnet.org/privacy-policy
> 
> # Additional Notes
> [ZURICH-#673229-v1-HOPR__privacy_statement_(e).DOCX.pdf](https://github.com/hoprnet/website-hoprnet-org/files/5584972/ZURICH-.673229-v1-HOPR__privacy_statement_.e.DOCX.pdf)

**Comment by 0xjjpa** [comment]
Solved in #154
