### ISSUE TITLE
Create TheGraph subgraph for HOP

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-website#22]
Currently blocked by our smart contract specification and implementation. Once this is done it should be relatively straightforward following their [documentation](https://thegraph.com/docs/define-a-subgraph).

**Comment by 0xjjpa** [comment]
Have done some work on this for [two](https://github.com/jjperezaguinaga/dai-token-tracker) [projects](https://github.com/jjperezaguinaga/the-kyber-whales) in the past in case you need help whenever this gets unblocked.

**Comment by SCBuergel** [comment]
Let's review that when we discuss indexer - and all edge cases such as reorg while HOPR node down

**Comment by 0xjjpa** [comment]
Sunsetting this as this should be on hoprnet and its currently not relevant.
