### ISSUE TITLE
Website Homepage

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-website#27]
Fixes #26 

sprint 7:
- [x] update `teamAndInvestors` section with new images
- [x] add border radius to all cards
- [x] update logo
- [x] update favicon
- [x] fix contact input place holder color
- [x] improve socials color
- [x] improve mobile UI
- [x] discuss `blogs` section
- [x] add `blogs` section
- [x] remove `lorem ipsum` and replace it with new text
- [x] remove description text from `HOPR for`, `HOPR is`, `HOPR Blog`
- [x] add email links to 35, 37
- [x] add more investors
- [x] add analytics
- [x] integrate medium blog
- [x] add urls to `footer` navigation
- [x] add `About us`
- [x] add `Governance`
- [x] add `Partner`
- [x] add `Investors`
- [x] add `Team`
- [x] add `Jobs`
- [x] add `Contact Us`
- [x] add header image
- [x] point blogs in homepage to blog section
- [x] fill open source section
- [x] integrate newsletter
- [x] bug: fix newsletter iframe height
- [x] Techies: link to gitbook
- [x] miners & relayers: link to gitbook
- [x] Enabling Data Privacy: link to We Are / Enabling Data Privacy
- [x] Open Source Support: link to We Are / Open Source Support
- [x] Hackathons & Community: link to We Are / Hackathons & Community
- [x] Hackathons & Community: space "events(coming"
- [x] Your company & our ecosystem: capitals
- [x] Tech + Blockchain Blog: Tech Blog
- [x] Partners: fix spacing on top
- [x] Investors: fix spacing on top
- [x] add kevin to team: https://www.linkedin.com/in/kevinleu/
- [x] we_are/This is how we do it: The HOPR protocol -> becomes title
- [x] we_are/This is how we do it: two columns
- [x] we_are/Open Source Support: smaller distance between title and text
- [x] Documentation: add "Find out more on how to join the HOPR network, run your own node and dive deeper into how to BUIDL with HOPR"
- [x] Hosted at gitbook: button
- [x] blog: https://medium.com/hoprnet
- [x] for_you: move to videos
- [x] header - text: same wide
- [x] improve text
- [x] navbar sticky
- [ ] update "HOPR is" section

optional:
- [ ] add `R Infos`
- [ ] add `FAQ` in `footer`

**Comment by nionis** [comment]
Closed by #26
