### ISSUE TITLE
Website Development/Updates

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-website#47]
- [x] add disclaimer
- [x] refactor repo to support two websites
- [x] deploy that one to HOPR.swiss
- [x] remove content from both websites
- [x] refactor HOPR.swiss
- [x] various updates (30/06/2020)
- [x] various updates (01/07/2020)
- [x] various updates (02/07/2020)
- [x] various updates (07/07/2020)

[changes preview](https://github.com/hoprnet/hopr-website/compare/e465328702c8b53885b814a8e0d27f55759b839d..fb3164f769e11de27019598e93215273592a5412)

**Comment by nionis** [comment]
I will keep this issue open until the end of this sprint

**Comment by nionis** [comment]
Closing this issue, we can open a new issue for next sprint.

**Comment by nionis** [comment]
Reopening this issue since we will stay on Spring 8 this week.

**Comment by nionis** [comment]
Closing this issue, we can open a new issue for next sprint.
