### ISSUE TITLE
hopr.swiss cannot build

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-website#97]
Due to our recent redesign, we had to make some breaking changes to the codebase, `hopr.swiss` no longer builds.
The two websites diverged alot, maybe we move them into seperate repos?

**Comment by nionis** [comment]
Last working commit for hopr.swiss 5baee71700176850ab2f2fd40fdfd170d9d1b722

**Comment by 0xjjpa** [comment]
Can you take a look at `website-hopr-swiss` to verify if this is still the case?

**Comment by 0xjjpa** [comment]
@nionis Ping 🏓

**Comment by nionis** [comment]
@jjperezaguinaga 

> Can you take a look at `website-hopr-swiss` to verify if this is still the case?

[website-hopr-swiss](https://github.com/hoprnet/website-hopr-swiss) successfully builds 👍

**Comment by 0xjjpa** [comment]
Great, thanks! Closing this one for the time being.
